/**
 * AI Recap panel for a single session.
 *
 * Mounts above the session player when a session is selected. Fetches
 * /sessions/:id/summary — a 200ms typical response on cache hit, up to
 * ~5s on LLM cold calls (same cache store as other briefs, 7-day TTL).
 *
 * Mode badge mirrors the AI/AUTO pattern from Session 2 portfolio brief.
 */
import React, { useEffect, useState } from 'react';
import { Sparkles, AlertTriangle, Lightbulb, ChevronDown, ChevronUp } from 'lucide-react';
import type { SessionAiSummary, SessionFrictionMoment } from '../../../../../packages/contracts/index';
import { fetchJson } from '../../lib/api';

interface Props {
  sessionId: string;
  sessionStartedAt?: string;
}

const FRICTION_LABELS: Record<SessionFrictionMoment['kind'], { label: string; accent: string }> = {
  rage_click: { label: 'Rage click', accent: 'bg-red-50 text-red-700 ring-red-200' },
  dead_click: { label: 'Dead click', accent: 'bg-amber-50 text-amber-700 ring-amber-200' },
  form_error: { label: 'Form error', accent: 'bg-orange-50 text-orange-700 ring-orange-200' },
  slow_lcp:   { label: 'Slow LCP',   accent: 'bg-rose-50 text-rose-700 ring-rose-200' },
  u_turn:     { label: 'U-turn',     accent: 'bg-violet-50 text-violet-700 ring-violet-200' },
};

const formatRelativeTs = (ts: number, startedAt?: string): string => {
  if (!ts || !startedAt) return '';
  const start = new Date(startedAt.replace(' ', 'T') + 'Z').getTime();
  const delta = Math.max(0, Math.round((ts - start) / 1000));
  const mins = Math.floor(delta / 60);
  const secs = delta % 60;
  if (mins === 0) return `${secs}s`;
  return `${mins}m ${secs}s`;
};

export const SessionSummaryPanel: React.FC<Props> = ({ sessionId, sessionStartedAt }) => {
  const [summary, setSummary] = useState<SessionAiSummary | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [expanded, setExpanded] = useState<boolean | null>(null);

  useEffect(() => {
    let mounted = true;
    setIsLoading(true);
    setError(null);
    fetchJson<SessionAiSummary>(`/sessions/${sessionId}/summary`)
      .then((data) => {
        if (!mounted) return;
        setSummary(data);
        // Auto-expand if LLM-generated (richer narrative). Deterministic starts collapsed.
        setExpanded((prev) => (prev === null ? data.mode === 'llm' : prev));
      })
      .catch((err) => {
        if (!mounted) return;
        setError(err instanceof Error ? err.message : 'Failed to load summary');
      })
      .finally(() => {
        if (mounted) setIsLoading(false);
      });
    return () => {
      mounted = false;
    };
  }, [sessionId]);

  if (isLoading) {
    return (
      <div className="rounded-2xl border border-surface-200 bg-white p-4 shadow-sm">
        <div className="flex items-center gap-2">
          <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-primary-100">
            <Sparkles className="h-4 w-4 text-primary-700" />
          </div>
          <div className="text-sm font-semibold text-surface-700">Generating AI recap…</div>
        </div>
      </div>
    );
  }

  if (error || !summary) {
    return null; // Silently hide if the endpoint errored — the player still works.
  }

  const isOpen = expanded ?? false;

  return (
    <div className="rounded-2xl border border-surface-200 bg-white p-4 shadow-sm">
      <div className="flex items-start gap-3">
        <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-primary-100 to-accent-100 text-primary-700 shrink-0">
          <Sparkles className="h-4 w-4" />
        </div>
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <h3 className="text-sm font-semibold text-surface-900">AI Recap</h3>
            <span
              className={`rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.18em] ${
                summary.mode === 'llm'
                  ? 'bg-primary-100 text-primary-700'
                  : 'bg-surface-100 text-surface-600'
              }`}
              title={summary.mode === 'llm' ? 'Generated by Claude Haiku' : 'Deterministic fallback (no LLM call)'}
            >
              {summary.mode === 'llm' ? 'AI' : 'Auto'}
            </span>
            <button
              type="button"
              onClick={() => setExpanded(!isOpen)}
              className="ml-auto inline-flex items-center gap-1 rounded-lg border border-surface-200 px-2 py-1 text-xs font-semibold text-surface-600 transition hover:border-primary-300 hover:text-primary-700"
            >
              {isOpen ? <ChevronUp className="h-3.5 w-3.5" /> : <ChevronDown className="h-3.5 w-3.5" />}
              {isOpen ? 'Collapse' : 'Expand'}
            </button>
          </div>

          <p className="mt-2 text-sm font-medium text-surface-900">{summary.headline}</p>

          {isOpen && (
            <>
              <p className="mt-3 text-sm text-surface-600 whitespace-pre-line">{summary.narrative}</p>

              {summary.frictionMoments.length > 0 && (
                <div className="mt-4 space-y-1.5">
                  <div className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-[0.16em] text-surface-500">
                    <AlertTriangle className="h-3.5 w-3.5" />
                    Friction Moments
                  </div>
                  <ul className="space-y-1.5">
                    {summary.frictionMoments.map((moment, idx) => {
                      const meta = FRICTION_LABELS[moment.kind] ?? FRICTION_LABELS.rage_click;
                      return (
                        <li
                          key={`${moment.ts}-${idx}`}
                          className="flex items-center gap-2 rounded-xl border border-surface-100 bg-surface-50 px-3 py-1.5 text-xs"
                        >
                          <span className={`rounded-full px-2 py-0.5 font-semibold ring-1 ${meta.accent}`}>
                            {meta.label}
                          </span>
                          {sessionStartedAt && (
                            <span className="font-mono text-[10px] text-surface-400">
                              {formatRelativeTs(moment.ts, sessionStartedAt)}
                            </span>
                          )}
                          <span className="text-surface-700 truncate">{moment.detail}</span>
                        </li>
                      );
                    })}
                  </ul>
                </div>
              )}

              {summary.opportunities.length > 0 && (
                <div className="mt-4 space-y-1.5">
                  <div className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-[0.16em] text-surface-500">
                    <Lightbulb className="h-3.5 w-3.5" />
                    Opportunities
                  </div>
                  <ul className="space-y-1.5">
                    {summary.opportunities.map((op, idx) => (
                      <li
                        key={idx}
                        className="rounded-xl border border-primary-100 bg-primary-50/50 px-3 py-2 text-xs"
                      >
                        <p className="font-semibold text-surface-900">{op.title}</p>
                        <p className="mt-0.5 text-surface-600">{op.rationale}</p>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );
};
