import { dataViz, fonts, motion, radius, semantic } from './index';

const vars = (obj: Record<string, string>, indent = '  ') =>
  Object.entries(obj)
    .map(([k, v]) => `${indent}--${k}: ${v};`)
    .join('\n');

const vizVars = (list: readonly string[]) => Object.fromEntries(list.map((c, i) => [`viz-${i + 1}`, c]));

/**
 * Renders the CSS consumed by Tailwind v4 (`@import "@pulse/tokens/tokens.css"`).
 * Light is the default; dark applies with prefers-color-scheme unless data-theme="light",
 * and always with data-theme="dark".
 */
export function renderTokensCss(): string {
  const light = { ...semantic.light, ...vizVars(dataViz.light) };
  const dark = { ...semantic.dark, ...vizVars(dataViz.dark) };
  const themeColors = Object.keys(light)
    .map((k) => `  --color-${k}: var(--${k});`)
    .join('\n');

  return `/* GENERATED by packages/tokens/scripts/build-css.ts — do not edit by hand. */
:root {
${vars(light)}
  color-scheme: light;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${vars(dark, '    ')}
    color-scheme: dark;
  }
}
:root[data-theme='dark'] {
${vars(dark)}
  color-scheme: dark;
}

@theme inline {
${themeColors}
  --font-sans: ${fonts.sans};
  --font-display: ${fonts.display};
  --font-mono: ${fonts.mono};
  --radius-sm: ${radius.sm}px;
  --radius-md: ${radius.md}px;
  --radius-lg: ${radius.lg}px;
  --radius-xl: ${radius.xl}px;
  --ease-pulse: ${motion.easing};
  --default-transition-duration: ${motion.fast}ms;
}
`;
}
