/**
 * DXM Pulse — ReportView
 * Decision-layer report UI: Key Takeaways → Primary Action → KPIs → Details.
 * User understands what to do in < 3 seconds.
 */

import React from 'react';
import { Link } from 'react-router-dom';
import {
  AlertTriangle,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  BarChart3,
  CheckCircle,
  Clock,
  FileText,
  Globe,
  Info,
  Lightbulb,
  Minus,
  Shield,
  Sparkles,
  Target,
  TrendingDown,
  XCircle,
  Zap,
} from 'lucide-react';
import type { Report, ReportMetric } from '../../lib/reportBuilder';

/* ── Style maps ──────────────────────────────────────────────────── */

const metricToneClasses = {
  positive: 'border-emerald-200 bg-emerald-50 text-emerald-800',
  neutral: 'border-surface-200 bg-surface-50 text-surface-800',
  warning: 'border-amber-200 bg-amber-50 text-amber-800',
} as const;

const severityConfig = {
  critical: { bg: 'bg-red-50', border: 'border-red-200', text: 'text-red-800', badge: 'bg-red-100 text-red-700', icon: XCircle },
  warning: { bg: 'bg-amber-50', border: 'border-amber-200', text: 'text-amber-800', badge: 'bg-amber-100 text-amber-700', icon: AlertTriangle },
  info: { bg: 'bg-blue-50', border: 'border-blue-200', text: 'text-blue-800', badge: 'bg-blue-100 text-blue-700', icon: Info },
} as const;

const priorityConfig = {
  high: { bg: 'bg-red-50', border: 'border-red-200', text: 'text-red-800', badge: 'bg-red-100 text-red-700' },
  medium: { bg: 'bg-amber-50', border: 'border-amber-200', text: 'text-amber-800', badge: 'bg-amber-100 text-amber-700' },
  low: { bg: 'bg-surface-50', border: 'border-surface-200', text: 'text-surface-700', badge: 'bg-surface-100 text-surface-600' },
} as const;

const confidenceConfig = {
  high: { label: 'High', color: 'text-emerald-700', bg: 'bg-emerald-50', border: 'border-emerald-200' },
  medium: { label: 'Medium', color: 'text-amber-700', bg: 'bg-amber-50', border: 'border-amber-200' },
  low: { label: 'Low', color: 'text-red-700', bg: 'bg-red-50', border: 'border-red-200' },
} as const;

/* ── Trend indicator with GOOD/BAD label ─────────────────────────── */

function TrendBadge({ metric }: { metric: ReportMetric }) {
  if (metric.change === null) return null;

  const absChange = Math.abs(metric.change);
  if (absChange < 1) {
    return (
      <span className="ml-1.5 inline-flex items-center gap-0.5 text-xs text-surface-400">
        <Minus className="h-3 w-3" />
        <span>0%</span>
      </span>
    );
  }

  const isIncrease = metric.change > 0;

  let isGood: boolean;
  if (metric.invertedTrend) {
    if (metric.label === 'Avg Duration') {
      isGood = isIncrease;
    } else {
      isGood = !isIncrease;
    }
  } else {
    isGood = isIncrease;
  }

  const colorClass = isGood ? 'text-emerald-700' : 'text-red-700';
  const bgClass = isGood ? 'bg-emerald-50' : 'bg-red-50';
  const Icon = isIncrease ? ArrowUp : ArrowDown;
  const sign = isIncrease ? '+' : '';
  const label = isGood ? 'GOOD' : 'BAD';

  return (
    <span className={`ml-1.5 inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[11px] font-semibold ${colorClass} ${bgClass}`}>
      <Icon className="h-3 w-3" />
      <span>{sign}{metric.change.toFixed(1)}%</span>
      <span className="opacity-70">{label}</span>
    </span>
  );
}

/* ── Props ────────────────────────────────────────────────────────── */

interface FrictionAlert {
  id: string;
  title: string;
  severity: string;
  affectedSessions: number;
}

interface ReportViewProps {
  report: Report;
  siteDomain: string;
  dateRange: string;
  aiSummary?: string | null;
  frictionAlerts?: FrictionAlert[];
}

/* ── Component ────────────────────────────────────────────────────── */

export const ReportView: React.FC<ReportViewProps> = ({ report, siteDomain, dateRange, aiSummary, frictionAlerts = [] }) => {
  const conf = confidenceConfig[report.confidence];

  return (
    <div className="dxm-report-panel space-y-6">
      {/* ── 1. Header + Confidence ───────────────────────────────── */}
      <header className="rounded-[28px] border border-primary-200 bg-white p-6 shadow-sm">
        <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div className="flex items-center gap-3">
            <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary-50">
              <Globe className="h-5 w-5 text-primary-600" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-surface-900">{siteDomain}</h1>
              <p className="mt-0.5 text-sm text-surface-500">{dateRange}</p>
            </div>
          </div>
          <div className="flex flex-col items-end gap-1.5">
            <div className="flex items-center gap-2 text-xs text-surface-400">
              <FileText className="h-3.5 w-3.5" />
              <span>Generated by DXM Pulse</span>
              <span className="text-surface-300">|</span>
              <span>{new Date(report.generatedAt).toLocaleDateString()}</span>
            </div>
            <div className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[11px] font-semibold ${conf.color} ${conf.bg} ${conf.border}`}>
              <Shield className="h-3 w-3" />
              <span>Confidence: {conf.label}</span>
              <span className="opacity-60">({report.sessionsAnalyzed} sessions)</span>
            </div>
          </div>
        </div>
      </header>

      {/* ── 2. Key Takeaways (decision in 3 seconds) ─────────────── */}
      <section className="rounded-[28px] border border-surface-200 bg-white p-6 shadow-sm">
        <div className="flex items-center gap-2">
          <Lightbulb className="h-4 w-4 text-primary-700" />
          <h2 className="text-xs font-semibold uppercase tracking-[0.18em] text-primary-700">Key Takeaways</h2>
        </div>
        <div className="mt-4 space-y-2">
          {report.keyTakeaways.positives.map((item, i) => (
            <div key={`p-${i}`} className="flex items-start gap-2.5 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3">
              <ArrowUp className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />
              <span className="text-sm font-medium text-emerald-800">{item}</span>
              <span className="ml-auto shrink-0 rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] font-bold text-emerald-700">GOOD</span>
            </div>
          ))}
          {report.keyTakeaways.negatives.map((item, i) => (
            <div key={`n-${i}`} className="flex items-start gap-2.5 rounded-2xl border border-red-200 bg-red-50 px-4 py-3">
              <ArrowDown className="mt-0.5 h-4 w-4 shrink-0 text-red-600" />
              <span className="text-sm font-medium text-red-800">{item}</span>
              <span className="ml-auto shrink-0 rounded-full bg-red-100 px-2 py-0.5 text-[10px] font-bold text-red-700">BAD</span>
            </div>
          ))}
          {report.keyTakeaways.primaryFocus && (
            <div className="mt-1 flex items-center gap-2 rounded-2xl border border-primary-200 bg-primary-50 px-4 py-3">
              <Target className="h-4 w-4 shrink-0 text-primary-700" />
              <span className="text-sm font-semibold text-primary-800">{report.keyTakeaways.primaryFocus}</span>
            </div>
          )}
        </div>
      </section>

      {/* ── 3. Primary Action Card ───────────────────────────────── */}
      {report.primaryAction && (
        <section className="rounded-[28px] border-2 border-primary-300 bg-primary-50 p-6 shadow-sm">
          <div className="flex items-center gap-2">
            <Target className="h-4 w-4 text-primary-700" />
            <h2 className="text-xs font-semibold uppercase tracking-[0.18em] text-primary-700">Priority Action</h2>
          </div>
          <h3 className="mt-3 text-lg font-bold text-surface-900">{report.primaryAction.title}</h3>
          <p className="mt-2 text-sm leading-relaxed text-surface-700">{report.primaryAction.detail}</p>
          {report.primaryAction.href && (
            <Link
              to={report.primaryAction.href}
              className="mt-4 inline-flex items-center gap-2 rounded-2xl bg-primary-600 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-primary-700"
            >
              <ArrowRight className="h-4 w-4" />
              View sessions
            </Link>
          )}
        </section>
      )}

      {/* ── 4. Executive Summary ─────────────────────────────────── */}
      <section className="rounded-[28px] border border-surface-200 bg-surface-50 p-6 shadow-sm">
        <div className="flex items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            {aiSummary ? (
              <Sparkles className="h-4 w-4 text-primary-600" />
            ) : (
              <Lightbulb className="h-4 w-4 text-surface-600" />
            )}
            <h2 className="text-xs font-semibold uppercase tracking-[0.18em] text-surface-600">Executive Summary</h2>
          </div>
          {aiSummary && (
            <span className="rounded-full bg-blue-100 px-2 py-0.5 text-[10px] font-bold text-blue-700">AI</span>
          )}
        </div>
        <p className="mt-4 text-sm leading-7 text-surface-700">{aiSummary ?? report.summary}</p>
      </section>

      {/* ── 4b. Friction Signals ─────────────────────────────────── */}
      {frictionAlerts.length > 0 && (
        <section className="rounded-[28px] border border-amber-200 bg-amber-50 p-6 shadow-sm">
          <div className="flex items-center gap-2">
            <Zap className="h-4 w-4 text-amber-600" />
            <h2 className="text-xs font-semibold uppercase tracking-[0.18em] text-amber-700">Friction Signals</h2>
            <span className="rounded-full bg-amber-100 px-2 py-0.5 text-xs font-semibold text-amber-700">
              {frictionAlerts.length} active
            </span>
          </div>
          <div className="mt-4 space-y-2">
            {frictionAlerts.map((alert) => (
              <div key={alert.id} className="flex items-center justify-between gap-3 rounded-2xl border border-amber-200 bg-white px-4 py-3">
                <span className="text-sm font-medium text-surface-800">{alert.title}</span>
                {alert.affectedSessions > 0 && (
                  <span className="shrink-0 rounded-full bg-amber-100 px-2.5 py-0.5 text-xs font-semibold text-amber-700">
                    {alert.affectedSessions} session{alert.affectedSessions !== 1 ? 's' : ''} affected
                  </span>
                )}
              </div>
            ))}
          </div>
        </section>
      )}

      {/* ── 5. KPI Summary with trends + GOOD/BAD labels ─────────── */}
      <section className="rounded-[28px] border border-surface-200 bg-white p-6 shadow-sm">
        <div className="flex items-center gap-2">
          <BarChart3 className="h-4 w-4 text-surface-600" />
          <h2 className="text-xs font-semibold uppercase tracking-[0.18em] text-surface-600">Key Metrics</h2>
          <span className="text-xs text-surface-400">vs previous 7 days</span>
        </div>
        <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {report.metrics.map((metric) => (
            <div
              key={metric.label}
              className={`rounded-2xl border p-4 ${metricToneClasses[metric.tone]}`}
            >
              <p className="text-xs font-semibold uppercase tracking-[0.15em] opacity-70">{metric.label}</p>
              <div className="mt-2 flex items-baseline flex-wrap gap-y-1">
                <p className="text-2xl font-bold">{metric.value}</p>
                <TrendBadge metric={metric} />
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ── 6. Insights Section ──────────────────────────────────── */}
      {report.insights.length > 0 && (
        <section className="rounded-[28px] border border-surface-200 bg-white p-6 shadow-sm">
          <div className="flex items-center gap-2">
            <AlertTriangle className="h-4 w-4 text-surface-600" />
            <h2 className="text-xs font-semibold uppercase tracking-[0.18em] text-surface-600">Insights</h2>
            <span className="rounded-full bg-surface-100 px-2 py-0.5 text-xs font-semibold text-surface-600">
              {report.insights.length}
            </span>
          </div>
          <div className="mt-4 space-y-3">
            {report.insights.map((insight) => {
              const config = severityConfig[insight.severity];
              const Icon = config.icon;
              return (
                <div
                  key={insight.title}
                  className={`rounded-2xl border p-4 ${config.border} ${config.bg}`}
                >
                  <div className="flex items-start gap-3">
                    <Icon className={`mt-0.5 h-4 w-4 shrink-0 ${config.text}`} />
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2">
                        <h3 className={`text-sm font-semibold ${config.text}`}>{insight.title}</h3>
                        <span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase ${config.badge}`}>
                          {insight.severity}
                        </span>
                      </div>
                      <p className="mt-1 text-sm leading-relaxed text-surface-600">{insight.description}</p>
                      {insight.recommendation && (
                        <div className="mt-2 flex items-start gap-1.5 rounded-xl bg-white/60 px-3 py-2">
                          <ArrowRight className="mt-0.5 h-3 w-3 shrink-0 text-surface-400" />
                          <p className="text-xs text-surface-600">{insight.recommendation}</p>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </section>
      )}

      {/* ── 7. Top Pages with bounce proxy ────────────────────────── */}
      {report.topPages.length > 0 && (
        <section className="rounded-[28px] border border-surface-200 bg-white p-6 shadow-sm">
          <div className="flex items-center gap-2">
            <Globe className="h-4 w-4 text-surface-600" />
            <h2 className="text-xs font-semibold uppercase tracking-[0.18em] text-surface-600">Top Pages</h2>
          </div>
          <div className="mt-4 overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-surface-200">
                  <th className="pb-3 text-left text-xs font-semibold uppercase tracking-[0.15em] text-surface-500">URL</th>
                  <th className="pb-3 text-right text-xs font-semibold uppercase tracking-[0.15em] text-surface-500">Sessions</th>
                  <th className="pb-3 text-right text-xs font-semibold uppercase tracking-[0.15em] text-surface-500">Avg Duration</th>
                  <th className="pb-3 text-right text-xs font-semibold uppercase tracking-[0.15em] text-surface-500">Bounce Proxy</th>
                </tr>
              </thead>
              <tbody>
                {report.topPages.map((page) => {
                  const isBounceHigh = page.bounceProxy !== null && page.bounceProxy >= 50;
                  return (
                    <tr key={page.url} className="border-b border-surface-100 last:border-0">
                      <td className="py-3 pr-4">
                        <span className="inline-block max-w-[360px] truncate text-surface-700">{page.url}</span>
                      </td>
                      <td className="py-3 text-right font-semibold text-surface-900">{page.sessions}</td>
                      <td className="py-3 text-right text-surface-600">
                        <span className="inline-flex items-center gap-1">
                          <Clock className="h-3 w-3" />
                          {page.avgDuration}
                        </span>
                      </td>
                      <td className="py-3 text-right">
                        {page.bounceProxy !== null ? (
                          <span className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-semibold ${
                            isBounceHigh
                              ? 'bg-red-50 text-red-700'
                              : 'bg-surface-50 text-surface-600'
                          }`}>
                            {page.bounceProxy}%
                            {isBounceHigh && <span className="text-[9px] opacity-70">BAD</span>}
                          </span>
                        ) : (
                          <span className="text-xs text-surface-300">—</span>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
            <p className="mt-2 text-[11px] text-surface-400">
              Bounce proxy = % of sessions under 10 seconds on this page. Higher values suggest visitors leave quickly.
            </p>
          </div>
        </section>
      )}

      {/* ── 8. Activity summary (compact) ────────────────────────── */}
      <section className="rounded-[28px] border border-surface-200 bg-white p-6 shadow-sm">
        <div className="flex items-center gap-2">
          <TrendingDown className="h-4 w-4 text-surface-600" />
          <h2 className="text-xs font-semibold uppercase tracking-[0.18em] text-surface-600">Activity Summary</h2>
        </div>
        <div className="mt-4 grid gap-3 sm:grid-cols-3">
          <div className="rounded-2xl bg-surface-50 p-4">
            <p className="text-xs font-semibold uppercase tracking-[0.15em] text-surface-500">Insights detected</p>
            <p className="mt-2 text-2xl font-bold text-surface-900">{report.insights.length}</p>
          </div>
          <div className="rounded-2xl bg-surface-50 p-4">
            <p className="text-xs font-semibold uppercase tracking-[0.15em] text-surface-500">Pages tracked</p>
            <p className="mt-2 text-2xl font-bold text-surface-900">{report.topPages.length}</p>
          </div>
          <div className="rounded-2xl bg-surface-50 p-4">
            <p className="text-xs font-semibold uppercase tracking-[0.15em] text-surface-500">Action items</p>
            <p className="mt-2 text-2xl font-bold text-surface-900">{report.recommendations.length}</p>
          </div>
        </div>
      </section>

      {/* ── 9. Recommendations ───────────────────────────────────── */}
      {report.recommendations.length > 0 && (
        <section className="rounded-[28px] border border-surface-200 bg-white p-6 shadow-sm">
          <div className="flex items-center gap-2">
            <CheckCircle className="h-4 w-4 text-surface-600" />
            <h2 className="text-xs font-semibold uppercase tracking-[0.18em] text-surface-600">Recommendations</h2>
          </div>
          <div className="mt-4 space-y-3">
            {report.recommendations.map((rec, idx) => {
              const config = priorityConfig[rec.priority];
              return (
                <div
                  key={idx}
                  className={`flex items-start gap-3 rounded-2xl border p-4 ${config.border} ${config.bg}`}
                >
                  <span className={`mt-0.5 shrink-0 rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase ${config.badge}`}>
                    {rec.priority}
                  </span>
                  <p className={`text-sm leading-relaxed ${config.text}`}>{rec.text}</p>
                </div>
              );
            })}
          </div>
        </section>
      )}

      {/* ── Print footer ─────────────────────────────────────────── */}
      <footer className="hidden print:block text-center text-xs text-surface-400 pt-4 border-t border-surface-200">
        Report generated by DXM Pulse on {new Date(report.generatedAt).toLocaleDateString()}
      </footer>
    </div>
  );
};
